# Generated by Django 4.1.3 on 2023-01-20 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='year_of_project',
            field=models.DateField(default=datetime.datetime(2023, 1, 20, 19, 47, 38, 998179, tzinfo=datetime.timezone.utc), verbose_name='year of project'),
        ),
    ]
