# Generated by Django 4.1.3 on 2023-01-23 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_solution_year_of_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='address',
            field=models.CharField(default='address', max_length=300),
        ),
        migrations.AlterField(
            model_name='solution',
            name='year_of_project',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 20, 13, 0, 515376, tzinfo=datetime.timezone.utc), verbose_name='year of project'),
        ),
    ]
